-- Insert dummy data into the "service" table
INSERT INTO public.service(
	id, name, created_at, updated_at)
	VALUES (1, 'Inspection', now(), now()),
    (2, 'Automobile', now(), now());

INSERT INTO public.core_service(
	id, "coreServiceName", "packageType", created_at, updated_at, "serviceId")
	VALUES 
	(1,'Body Frame Accident Checklist', 'Basic',now(),now(), 1),
    (2,'Engine / Transmission / Clutch', 'Basic',now(),now(), 1),
    (3,'Brakes', 'Basic',now(),now(), 1),
    (4,'Suspension / Steering', 'Basic',now(),now(), 1),
    (5,'Interior', 'Basic',now(),now(), 1),
    (6,'AC / Heater', 'Premium',now(),now(), 1),
    (7,'Electrical / Electronics', 'Premium',now(),now(), 1),
    (8,'Exterior / Body', 'Premium',now(),now(), 1),
    (9,'Tyres', 'Premium',now(),now(), 1);

INSERT INTO public.sub_services(
    id, "subServiceName", "parentId", created_at, updated_at, "coreServicesId", imageable)
VALUES  
    (1,'Radiator Core Support', NULL, now(), now(), 1, true),
    (2,'Right Strut Tower Apron', NULL, now(), now(), 1, true),
    (3,'Left Strut Tower Apron', NULL, now(), now(), 1, true),
    (4,'Right Front Rail', NULL, now(), now(), 1, true),
    (5,'Left Front Rail', NULL, now(), now(), 1, true),
    (6,'Cowl Panel Firewall', NULL, now(), now(), 1, true),
    (7,'Right A Pillar', NULL, now(), now(), 1, true),
    (8,'Left A Pillar', NULL, now(), now(), 1, true),
    (9,'Right B Pillar', NULL, now(), now(), 1, true),
    (10,'Left B Pillar', NULL, now(), now(), 1, true),
    (11,'Right C Pillar', NULL, now(), now(), 1, true),
    (12,'Left C Pillar', NULL, now(), now(), 1, true),
    (13,'Boot Floor', NULL, now(), now(), 1, true),
    (14,'Boot Lock Pillar', NULL, now(), now(), 1, true),
    (15,'Front Subframe', NULL, now(), now(), 1, true),
    (16,'Rear Subframe', NULL, now(), now(), 1, true),
    (17,'Fluids/filters check', NULL, now(), now(), 2, false),
    (18,'Engine Oil Level', 17, now(), now(), 2, false),
    (19,'Engine Oil Leakage', 17, now(), now(), 2, true),
    (20,'Transmission Oil Leakage', 17, now(), now(), 2, true),
    (21,'Coolant Leakage', 17, now(), now(), 2, true),
    (22,'Brake Oil Leakage', 17, now(), now(), 2, true),
    (23,'Exhaust check', NULL, now(), now(), 2, false),
    (24,'Exhaust Sound', 23, now(), now(), 2, false),
    (25,'Mechanical check', NULL, now(), now(), 2, false),
    (26,'Belts', 25, now(), now(), 2, true),
    (27,'Wires', 25, now(), now(), 2, true),
    (28,'Engine Blow', 25, now(), now(), 2, false),
    (29,'Engine Noise', 25, now(), now(), 2, false),
    (30,'Engine Vibration', 25, now(), now(), 2, false),
    (31,'Engine Mounts', 25, now(), now(), 2, false),
    (32,'Pulleys (Adjuster)', 25, now(), now(), 2, false),
    (33,'Hoses', 25, now(), now(), 2, true),
    (34,'Engine cooling system', NULL, now(), now(), 2, true),
    (35,'Radiator', 34, now(), now(), 2, true),
    (36,'Suction Fan', 34, now(), now(), 2, true),
    (37,'Engine electronics', NULL, now(), now(), 2, false),
    (38,'Starter Operation', 37, now(), now(), 2, false),
    (39,'Front Right Disc', NULL, now(), now(), 3, false),
    (40,'Front Left Disc', NULL, now(), now(), 3, false),
    (41,'Parking / Hand Brake', NULL, now(), now(), 3, false),
    (42,'Front suspension', NULL, now(), now(), 4, false),
    (43,'Steering Wheel Play', 42, now(), now(), 4, false),
    (44,'Right Ball Joint', 42, now(), now(), 4, false),
    (45,'Left Ball Joint', 42, now(), now(), 4, false),
    (46,'Right Z Links', 42, now(), now(), 4, false),
    (47,'Left Z Links', 42, now(), now(), 4, false),
    (48,'Right Tie Rod End', 42, now(), now(), 4, false),
    (49,'Left Tie Rod End', 42, now(), now(), 4, false),
    (50,'Front Right Boots', 42, now(), now(), 4, false),
    (51,'Front Right Bushes', 42, now(), now(), 4, false),
    (52,'Front Left Bushes', 42, now(), now(), 4, false),
    (53,'Front Right Shock', 42, now(), now(), 4, false),
    (54,'Front Left Shock', 42, now(), now(), 4, false),
    (55,'Rear suspension', NULL, now(), now(), 4, false),
    (56,'Rear Right Bushes', 55, now(), now(), 4, false),
    (57,'Rear Left Bushes', 55, now(), now(), 4, false),
    (58,'Rear Right Shock', 55, now(), now(), 4, false),
    (59,'Rear Left Shock', 55, now(), now(), 4, false),
    (60,'Steering controls', NULL, now(), now(), 5, false),
    (61,'Steering Wheel Condition', 60, now(), now(), 5, false),
    (62,'Horn', 60, now(), now(), 5, false),
    (63,'Lights Lever / Switch', 60, now(), now(), 5, false),
    (64,'Wiper / Washer Lever', 60, now(), now(), 5, false),
    (65,'Mirrors', NULL, now(), now(), 5, false),
    (66,'Right Side Mirror', 65, now(), now(), 5, false),
    (67,'Left Side Mirror', 65, now(), now(), 5, false),
    (68,'Rear View Mirror Dimmer', 65, now(), now(), 5, false),
    (69,'Seats', NULL, now(), now(), 5, false),
    (70,'Right Seat Adjuster Recliner', 69, now(), now(), 5, false),
    (71,'Left Seat Adjuster Recliner', 69, now(), now(), 5, false),
    (72,'Right Seat Adjuster Lear Track', 69, now(), now(), 5, false),
    (73,'Left Seat Adjuster Lear Track', 69, now(), now(), 5, false),
    (74,'Right Seat Belt', 69, now(), now(), 5, false),
    (75,'Left Seat Belt', 69, now(), now(), 5, false),
    (76,'Rear Seat Belts', 69, now(), now(), 5, false),
    (77,'Glove Box', 69, now(), now(), 5, false),
    (78,'Power / manual windows & central locking', NULL, now(), now(), 5, false),
    (79,'Front Right Power Window/Manual Lever', 78, now(), now(), 5, false),
    (80,'Front Left Power Window/Manual Lever', 78, now(), now(), 5, false),
    (81,'Rear Right Power Window/Manual Lever', 78, now(), now(), 5, false),
    (82,'Rear Left Power Window/Manual Lever', 78, now(), now(), 5, false),
    (83,'Window Safety Lock', 78, now(), now(), 5, false),
    (84,'Dash / roof controls', NULL, now(), now(), 5, false),
    (85,'Interior Lightings', 84, now(), now(), 5, false),
    (86,'Dash Controls - A/C', 84, now(), now(), 5, true),
    (87,'Dash Controls - De-Fog', 84, now(), now(), 5, true),
    (88,'Dash Controls - Hazard Lights', 84, now(), now(), 5, false),
    (89,'Dash Controls - Others', 84, now(), now(), 5, false),
    (90,'Audio / Video', 84, now(), now(), 5, true),
    (91,'Trunk Release Lever / Button', 84, now(), now(), 5, false),
    (92,'Fuel Cap Release Lever / Button', 84, now(), now(), 5, false),
    (93,'Poshish', NULL, now(), now(), 5, true),
    (94,'Roof Poshish', 93, now(), now(), 5, true),
    (95,'Floor Mat', 93, now(), now(), 5, true),
    (96,'Front Right Seat Poshish', 93, now(), now(), 5, true),
    (97,'Front Left Seat Poshish', 93, now(), now(), 5, true),
    (98,'Rear Seat Poshish', 93, now(), now(), 5, true),
    (99,'Dashboard Condition', 93, now(), now(), 5, false),
    (100,'Equipment', NULL, now(), now(), 5, false),
    (101,'Spare Tire', 100, now(), now(), 5, false),
    (102,'Tools', 100, now(), now(), 5, false),
    (103,'Jack', 100, now(), now(), 5, false),
    (104,'Ac / heater check up', NULL, now(), now(), 6, false),
    (105,'AC Fitted', 104, now(), now(), 6, true),
    (106,'AC Operational', 104, now(), now(), 6, true),
    (107,'Blower', 104, now(), now(), 6, false),
    (108,'Cooling', 104, now(), now(), 6, false),
    (109,'Heating', 104, now(), now(), 6, false),
    (110,'Computer check up', NULL, now(), now(), 7, false),
    (111,'Computer Check up / Malfunction Check', 110, now(), now(), 7, false),
    (112,'Battery Warning Light', 110, now(), now(), 7, false),
    (113,'Oil Pressure Low Warning Light', 110, now(), now(), 7, false),
    (114,'Temperature Warning Light / Gauge', 110, now(), now(), 7, false),
    (115,'Power Steering Warning Light', 110, now(), now(), 7, false),
    (116,'Battery', NULL, now(), now(), 7, false),
    (117,'Voltage', 116, now(), now(), 7, false),
    (118,'Terminals Condition', 116, now(), now(), 7, false),
    (119,'Charging', 116, now(), now(), 7, false),
    (120,'Alternator Operation', 116, now(), now(), 7, false),
    (121,'Instrument cluster', NULL, now(), now(), 7, true),
    (122,'Gauges', 121, now(), now(), 7, true),
    (123,'Car frame', NULL, now(), now(), 8, true),
    (124,'Trunk Lock', 123, now(), now(), 8, true),
    (125,'Front Windshield Condition', 123, now(), now(), 8, true),
    (126,'Rear Windshield Condition', 123, now(), now(), 8, true),
    (127,'Front Right Door Window', 123, now(), now(), 8, true),
    (128,'Front Left Door Window', 123, now(), now(), 8, true),
    (129,'Rear Right Door Window', 123, now(), now(), 8, true),
    (130,'Rear Left Door Window', 123, now(), now(), 8, true),
    (131,'Windscreen Wiper', 123, now(), now(), 8, true),
    (132,'Exterior lights', NULL, now(), now(), 8, true),
    (133,'Right Headlight (Working)', 132, now(), now(), 8, true),
    (134,'Left Headlight (Working)', 132, now(), now(), 8, true),
    (135,'Right Headlight (Condition)', 132, now(), now(), 8, true),
    (136,'Left Headlight (Condition)', 132, now(), now(), 8, true),
    (137,'Right Taillight (Working)', 132, now(), now(), 8, true),
    (138,'Left Taillight (Working)', 132, now(), now(), 8, true),
    (139,'Right Taillight (Condition)', 132, now(), now(), 8, true),
    (140,'Left Taillight (Condition)', 132, now(), now(), 8, true),
    (141,'Front Right Tyre', NULL, now(), now(), 9, true),
    (142,'Front Left Tyre', NULL, now(), now(), 9, true),
    (143,'Rear Right Tyre', NULL, now(), now(), 9, true),
    (144,'Rear Left Tyre', NULL, now(), now(), 9, true),
    (145,'Rims', NULL, now(), now(), 9, true),
    (146,'Wheel Caps', NULL, now(), now(), 9, true),
    (147,'Front Left Boots', 42, now(), now(), 4, false),
    (148,'Bonnet Release Lever / Button', 84, now(), now(), 5, false);

   